### ISSUE TITLE
无法查看文章详情

### ISSUE THREAD

**Issue by guizimo** [liuzhihang/halo-theme-hao#201]
### 是什么版本出现了此问题？

1.1.3

### 在线站点地址

https://liuzhihang.com/

### 发生了什么？

无法查看文章详情，后台编辑文章也无法预览

### 相关日志输出

```shell
Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at Object.showLoading (heo.js:346:47)
    at HTMLDocument.<anonymous> (VM247 blogex.js:762:9)
    at pjax.min.js:1:8641
    at module.exports (pjax.min.js:1:9395)
    at pjax.min.js:1:8504
    at Array.forEach (<anonymous>)
    at module.exports (pjax.min.js:1:8314)
    at Pjax.loadUrl (pjax.min.js:1:4234)
    at Pjax.linkAction (pjax.min.js:1:14266)
    at HTMLAnchorElement.<anonymous> (pjax.min.js:1:14907)
```

### 附加信息

<img width="611" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/75361847/e2b935ca-34c4-4ecf-9316-b689f6ad0643">

**Comment by liuzhihang** [comment]
把后台配置点一点保存按钮，估计是配置那里没刷新
