### ISSUE TITLE
无法切换到hao主题

### ISSUE THREAD

**Issue by forealmy** [liuzhihang/halo-theme-hao#265]
### 是什么版本出现了此问题？

release 1.1.6

### 在线站点地址

http://47.115.208.45/

### 发生了什么？

刚搭建的halo，默认的earth主题不会出现问题，就是切换到hao时 服务器500，日志导出来了，不知道什么问题。

### 相关日志输出

```shell
2023-07-11T17:33:32.227+08:00  INFO 7 --- [reactor-tcp-epoll-2] org.wltea.analyzer.dic.Dictionary        : 加载扩展停止词典:org/wltea/analyzer/dic/stopword.dic
2023-07-11T17:33:32.556+08:00  WARN 7 --- [run.halo.app.core.extension.reconciler.SinglePageReconciler-t-1] r.h.a.e.controller.DefaultController     : Optimistic locking failure when reconciling request: run.halo.app.core.extension.reconciler.SinglePageReconciler-worker-1/Request[name=373a5f79-f44f-441a-9df1-85a4f553ece8]
2023-07-11T17:33:33.474+08:00 ERROR 7 --- [reactor-http-epoll-2] a.w.r.e.AbstractErrorWebExceptionHandler : [eac70668-109]  500 Server Error for HTTP POST "/apis/api.console.halo.run/v1alpha1/plugins/install"

java.lang.NullPointerException: Inflater has been closed
	at java.base/java.util.zip.Inflater.ensureOpen(Unknown Source) ~[na:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ run.halo.app.security.InitializeRedirectionWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ run.halo.app.security.authentication.login.UsernamePasswordLogoutHandler [DefaultWebFilterChain]
	*__checkpoint ⇢ run.halo.app.security.authentication.login.DelegatingLogoutPageGeneratingWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ run.halo.app.security.authentication.login.UsernamePasswordAuthenticator [DefaultWebFilterChain]
	*__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ AnonymousAuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ CsrfWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ CorsWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ OrderedWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ OrderedWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ OrderedWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP POST "/apis/api.console.halo.run/v1alpha1/plugins/install" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at java.base/java.util.zip.Inflater.ensureOpen(Unknown Source) ~[na:na]
		at java.base/java.util.zip.Inflater.inflate(Unknown Source) ~[na:na]
		at java.base/java.util.zip.InflaterInputStream.read(Unknown Source) ~[na:na]
		at java.base/java.io.FilterInputStream.read(Unknown Source) ~[na:na]
		at java.base/java.io.PushbackInputStream.read(Unknown Source) ~[na:na]
		at java.base/sun.nio.cs.StreamDecoder.readBytes(Unknown Source) ~[na:na]
		at java.base/sun.nio.cs.StreamDecoder.implRead(Unknown Source) ~[na:na]
		at java.base/sun.nio.cs.StreamDecoder.read(Unknown Source) ~[na:na]
		at java.base/java.io.InputStreamReader.read(Unknown Source) ~[na:na]
		at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:118) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:176) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:169) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:129) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1241) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:345) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:263) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:662) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:239) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:208) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:357) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:336) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:311) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:212) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:357) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:336) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:311) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:212) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:134) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:168) ~[snakeyaml-1.33.jar:na]
		at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:499) ~[snakeyaml-1.33.jar:na]
		at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:199) ~[spring-beans-6.0.10.jar:6.0.10]
		at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:166) ~[spring-beans-6.0.10.jar:6.0.10]
		at run.halo.app.infra.utils.YamlUnstructuredLoader.load(YamlUnstructuredLoader.java:44) ~[classes/:na]
		at run.halo.app.plugin.YamlPluginFinder.unstructuredToPlugin(YamlPluginFinder.java:99) ~[classes/:2.7.0]
		at run.halo.app.plugin.YamlPluginFinder.readPluginDescriptor(YamlPluginFinder.java:90) ~[classes/:2.7.0]
		at run.halo.app.plugin.YamlPluginFinder.find(YamlPluginFinder.java:65) ~[classes/:2.7.0]
		at run.halo.app.core.extension.service.impl.PluginServiceImpl.lambda$getPresets$0(PluginServiceImpl.java:62) ~[classes/:2.7.0]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:283) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxArray$ArrayConditionalSubscription.fastPath(FluxArray.java:340) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxArray$ArrayConditionalSubscription.request(FluxArray.java:263) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.request(FluxMapFuseable.java:360) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.request(FluxMapFuseable.java:360) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxFilter$FilterSubscriber.request(FluxFilter.java:186) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.MonoNext$NextSubscriber.request(MonoNext.java:108) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.request(FluxHide.java:152) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2341) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2215) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onSubscribe(FluxHide.java:122) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.MonoNext$NextSubscriber.onSubscribe(MonoNext.java:70) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxFilter$FilterSubscriber.onSubscribe(FluxFilter.java:85) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onSubscribe(FluxMapFuseable.java:265) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onSubscribe(FluxMapFuseable.java:265) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxArray.subscribe(FluxArray.java:50) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxArray.subscribe(FluxArray.java:59) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4495) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:203) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4480) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:200) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:337) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:354) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2071) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:145) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onComplete(FluxConcatMapNoPrefetch.java:240) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.checkTerminated(FluxWindowPredicate.java:540) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.drainLoop(FluxWindowPredicate.java:488) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.drain(FluxWindowPredicate.java:432) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onComplete(FluxWindowPredicate.java:312) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxCreate$BaseSink.complete(FluxCreate.java:460) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:805) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxCreate$BufferAsyncSink.complete(FluxCreate.java:753) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxCreate$SerializedFluxSink.drainLoop(FluxCreate.java:247) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxCreate$SerializedFluxSink.drain(FluxCreate.java:213) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxCreate$SerializedFluxSink.complete(FluxCreate.java:204) ~[reactor-core-3.5.7.jar:3.5.7]
		at org.springframework.http.codec.multipart.MultipartParser.emitComplete(MultipartParser.java:185) ~[spring-web-6.0.10.jar:6.0.10]
		at org.springframework.http.codec.multipart.MultipartParser$HeadersState.onNext(MultipartParser.java:383) ~[spring-web-6.0.10.jar:6.0.10]
		at org.springframework.http.codec.multipart.MultipartParser.changeState(MultipartParser.java:149) ~[spring-web-6.0.10.jar:6.0.10]
		at org.springframework.http.codec.multipart.MultipartParser$BodyState.onNext(MultipartParser.java:562) ~[spring-web-6.0.10.jar:6.0.10]
		at org.springframework.http.codec.multipart.MultipartParser.changeState(MultipartParser.java:149) ~[spring-web-6.0.10.jar:6.0.10]
		at org.springframework.http.codec.multipart.MultipartParser$HeadersState.onNext(MultipartParser.java:398) ~[spring-web-6.0.10.jar:6.0.10]
		at org.springframework.http.codec.multipart.MultipartParser.changeState(MultipartParser.java:149) ~[spring-web-6.0.10.jar:6.0.10]
		at org.springframework.http.codec.multipart.MultipartParser$BodyState.onNext(MultipartParser.java:562) ~[spring-web-6.0.10.jar:6.0.10]
		at org.springframework.http.codec.multipart.MultipartParser.changeState(MultipartParser.java:149) ~[spring-web-6.0.10.jar:6.0.10]
		at org.springframework.http.codec.multipart.MultipartParser$HeadersState.onNext(MultipartParser.java:398) ~[spring-web-6.0.10.jar:6.0.10]
		at org.springframework.http.codec.multipart.MultipartParser.changeState(MultipartParser.java:149) ~[spring-web-6.0.10.jar:6.0.10]
		at org.springframework.http.codec.multipart.MultipartParser$PreambleState.onNext(MultipartParser.java:328) ~[spring-web-6.0.10.jar:6.0.10]
		at org.springframework.http.codec.multipart.MultipartParser.hookOnNext(MultipartParser.java:120) ~[spring-web-6.0.10.jar:6.0.10]
		at org.springframework.http.codec.multipart.MultipartParser.hookOnNext(MultipartParser.java:52) ~[spring-web-6.0.10.jar:6.0.10]
		at reactor.core.publisher.BaseSubscriber.onNext(BaseSubscriber.java:160) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:292) ~[reactor-netty-core-1.1.8.jar:1.1.8]
		at reactor.netty.channel.FluxReceive.request(FluxReceive.java:131) ~[reactor-netty-core-1.1.8.jar:1.1.8]
		at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:164) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:164) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.BaseSubscriber.request(BaseSubscriber.java:214) ~[reactor-core-3.5.7.jar:3.5.7]
		at org.springframework.http.codec.multipart.MultipartParser.requestBuffer(MultipartParser.java:193) ~[spring-web-6.0.10.jar:6.0.10]
		at org.springframework.http.codec.multipart.MultipartParser.hookOnSubscribe(MultipartParser.java:114) ~[spring-web-6.0.10.jar:6.0.10]
		at reactor.core.publisher.BaseSubscriber.onSubscribe(BaseSubscriber.java:148) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:92) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onSubscribe(FluxPeek.java:171) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.core.publisher.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:92) ~[reactor-core-3.5.7.jar:3.5.7]
		at reactor.netty.channel.FluxReceive.startReceiver(FluxReceive.java:170) ~[reactor-netty-core-1.1.8.jar:1.1.8]
		at reactor.netty.channel.FluxReceive.lambda$subscribe$2(FluxReceive.java:148) ~[reactor-netty-core-1.1.8.jar:1.1.8]
		at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.94.Final.jar:4.1.94.Final]
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.94.Final.jar:4.1.94.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.94.Final.jar:4.1.94.Final]
		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.94.Final.jar:4.1.94.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.94.Final.jar:4.1.94.Final]
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.94.Final.jar:4.1.94.Final]
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.94.Final.jar:4.1.94.Final]
		at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

### 附加信息

![image](https://github.com/liuzhihang/halo-theme-hao/assets/34614792/efa0c736-e02d-412c-9c64-89715272525f)

**Comment by chengzhongxue** [comment]
配置全部保存一遍

**Comment by forealmy** [comment]
> 配置全部保存一遍

了解
