### ISSUE TITLE
切换主题后出现500服务器内部错误

### ISSUE THREAD

**Issue by xiangchu95** [liuzhihang/halo-theme-hao#271]
### 是什么版本出现了此问题？

1.1.6

### 在线站点地址

https://blog-dev.xiangchu.tk

### 发生了什么？

![image](https://github.com/liuzhihang/halo-theme-hao/assets/110237853/6a4dbe02-6aca-4a63-9d97-67e2c3b8787a)

### 相关日志输出

```shell
halo-halo-1  | 2023-07-12T18:07:15.996+08:00 ERROR 6 --- [oundedElastic-5] a.w.r.e.AbstractErrorWebExceptionHandler : [a6b13926-96]  500 Server Error for HTTP GET "/"
halo-halo-1  | 
halo-halo-1  | org.thymeleaf.exceptions.TemplateInputException: Error resolving template [modules/bar/null], template might not exist or might not be accessible by any of the configured Template Resolvers (template: "index" - line 22, col 22)
halo-halo-1  |  at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
halo-halo-1  |  Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
halo-halo-1  | Error has been observed at the following site(s):
halo-halo-1  |  *__checkpoint ⇢ Handler run.halo.app.theme.router.factories.IndexRouteFactory$$Lambda$2547/0x0000000801a4ceb0@2fab378 [DispatcherHandler]
halo-halo-1  |  *__checkpoint ⇢ run.halo.app.security.InitializeRedirectionWebFilter [DefaultWebFilterChain]
halo-halo-1  |  *__checkpoint ⇢ run.halo.app.security.authentication.login.UsernamePasswordLogoutHandler [DefaultWebFilterChain]
halo-halo-1  |  *__checkpoint ⇢ run.halo.app.security.authentication.login.DelegatingLogoutPageGeneratingWebFilter [DefaultWebFilterChain]
halo-halo-1  |  *__checkpoint ⇢ run.halo.app.security.authentication.login.UsernamePasswordAuthenticator [DefaultWebFilterChain]
halo-halo-1  |  *__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
halo-halo-1  |  *__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
halo-halo-1  |  *__checkpoint ⇢ HTTP GET "/" [ExceptionHandlingWebHandler]
halo-halo-1  | Original Stack Trace:
halo-halo-1  |          at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
halo-halo-1  |          at org.thymeleaf.engine.TemplateManager.parseStandalone(TemplateManager.java:250) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
halo-halo-1  |          at org.thymeleaf.standard.expression.FragmentExpression.resolveExecutedFragmentExpression(FragmentExpression.java:567) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
halo-halo-1  |          at org.thymeleaf.standard.processor.AbstractStandardFragmentInsertionTagProcessor.computeFragment(AbstractStandardFragmentInsertionTagProcessor.java:419) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
halo-halo-1  |          at org.thymeleaf.standard.processor.AbstractStandardFragmentInsertionTagProcessor.doProcess(AbstractStandardFragmentInsertionTagProcessor.java:115) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
halo-halo-1  |          at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
halo-halo-1  |          at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
halo-halo-1  |          at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
halo-halo-1  |          at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
halo-halo-1  |          at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
halo-halo-1  |          at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
halo-halo-1  |          at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1587) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
halo-halo-1  |          at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
halo-halo-1  |          at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
halo-halo-1  |          at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1587) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
halo-halo-1  |          at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
halo-halo-1  |          at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
halo-halo-1  |          at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:592) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
halo-halo-1  |          at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
halo-halo-1  |          at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077) ~[thymeleaf-3.1.1.RELEASE.jar:3.1.1.RELEASE]
halo-halo-1  |          at org.thymeleaf.spring6.SpringWebFluxTemplateEngine.lambda$createFullStream$0(SpringWebFluxTemplateEngine.java:198) ~[thymeleaf-spring6-3.1.1.RELEASE.jar:3.1.1.RELEASE]
halo-halo-1  |          at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:58) ~[reactor-core-3.5.7.jar:3.5.7]
halo-halo-1  |          at reactor.core.publisher.Mono.subscribe(Mono.java:4495) ~[reactor-core-3.5.7.jar:3.5.7]
halo-halo-1  |          at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.5.7.jar:3.5.7]
halo-halo-1  |          at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.7.jar:3.5.7]
halo-halo-1  |          at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.7.jar:3.5.7]
halo-halo-1  |          at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
halo-halo-1  |          at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
halo-halo-1  |          at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
halo-halo-1  |          at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
halo-halo-1  |          at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
halo-halo-1  | 
halo-halo-1  |
```

### 附加信息
![image](https://github.com/liuzhihang/halo-theme-hao/assets/110237853/d2eb6e8f-62f2-4385-a25d-6783273d9fc4)

_No response_

**Comment by lanbinshijie** [comment]
可以尝试点击主题的设置将每一个选项卡都点击一次保存试试

**Comment by xiangchu95** [comment]
这是什么操作 可以了

**Comment by sun0225SUN** [comment]
刚上传主题或者更新主题时，一些配置信息Halo并没有保存起来，有些信息不可缺省，缺省则会报错。所以必须手动保存下，这个问题可能会在不久的将来修复。

**Comment by liuzhihang** [comment]
<img width="2552" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/26057042/caebc283-77ba-4a10-95cb-7d0d8774ca56">

1. 登录自己的 Halo 后台，xxx/console
2. 找到主题
3. 主题的所有设置都点击下保存（新添加的功能需要点一下保存，有时候可能改了部分功能，建议还是全都点一遍）
