### ISSUE TITLE
手贱把那个 主菜单给删了 然后重新创建之后页面就打不开了

### ISSUE THREAD

**Issue by fl1906** [liuzhihang/halo-theme-hao#604]
### 是什么版本出现了此问题？

1.4.6

### 在线站点地址

https://blog.flya.top

### 发生了什么？

![image](https://github.com/liuzhihang/halo-theme-hao/assets/73702449/7d722148-a8ce-4eb0-8d92-b2a9098d55e3)
![image](https://github.com/liuzhihang/halo-theme-hao/assets/73702449/9a760efb-0ca0-4393-abf2-28278848d93f)

但是切换到其他的主题都能正常打开，刷新缓存和每一个点击保存都试过了，没什么用..
![image](https://github.com/liuzhihang/halo-theme-hao/assets/73702449/c4bcfd75-6024-420c-bdd6-c9ba391f4f68)

### 相关日志输出

```shell
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: run.halo.app.infra.exception.NotFoundException: 404 NOT_FOUND "Menu with name menu-qvVQM not found"
	at run.halo.app.theme.finders.impl.MenuFinderImpl.lambda$getByName$1(MenuFinderImpl.java:47) ~[classes/:2.10.0]
	at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55) ~[reactor-core-3.5.10.jar:3.5.10]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4495) ~[reactor-core-3.5.10.jar:3.5.10]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82) ~[reactor-core-3.5.10.jar:3.5.10]
	at reactor.core.publisher.MonoNext$NextSubscriber.onComplete(MonoNext.java:102) ~[reactor-core-3.5.10.jar:3.5.10]
	at reactor.core.publisher.FluxFilter$FilterSubscriber.onComplete(FluxFilter.java:166) ~[reactor-core-3.5.10.jar:3.5.10]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:260) ~[reactor-core-3.5.10.jar:3.5.10]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:152) ~[reactor-core-3.5.10.jar:3.5.10]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:152) ~[reactor-core-3.5.10.jar:
```

**Comment by carolcoral** [comment]
试试新建主菜单后，然后在主题中重新绑定主菜单。看日志是因为绑定的主菜单id `menu-qvVQM`不存在导致的，可能需要你重新绑定新的菜单ID

**Comment by fl1906** [comment]
> 试试新建主菜单后，然后在主题中重新绑定主菜单。看日志是因为绑定的主菜单id `menu-qvVQM`不存在导致的，可能需要你重新绑定新的菜单ID


还是不行，问题定位在这里：
<img width="1404" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/73702449/a140d1cb-a523-4451-a553-a02c989e90fd">
<img width="1368" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/73702449/2da3d517-d8b1-421a-9934-811c0f6d0348">
org.thymeleaf.exceptions.TemplateProcessingException: Error during execution of processor 'org.thymeleaf.standard.processor.StandardWithTagProcessor' (template: "modules/sidebar" - line 14, col 19)
        at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:117) ~[thymeleaf-3.1.2.RELEASE.jar:3.1.2.RELEASE]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):

**Comment by fl1906** [comment]
<img width="1018" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/73702449/24011a75-6692-4ea3-be5e-faf901ff611b">

**Comment by carolcoral** [comment]
你在“主题”-“导航”中左侧菜单重新勾选下新菜单试试呢

**Comment by fl1906** [comment]
可以了，谢谢
