### ISSUE TITLE
关于评论提醒的bug

### ISSUE THREAD

**Issue by Orange-AFK** [liuzhihang/halo-theme-hao#676]
### 是什么版本出现了此问题？

 1.4.8

### 在线站点地址

https://apoptoxin4869.com/

### 发生了什么？

你好，关于评论提醒的bug我已向评论插件仓库（https://github.com/halo-dev/plugin-comment-widget/issues/90）以及halo仓库（https://github.com/halo-dev/halo/issues/5454）提交了issue，得到回复主题有可能引起此bug（https://github.com/halo-dev/plugin-comment-widget/issues/90#issuecomment-1980229242）

**以下是原文：**
1.访客及注册账户在自定义模板页面留下评论，邮件提醒未收到，但在文章页面留下评论可以正常收到；评论均会显示在管理后台中，此处显示”未知“位置的评论是在自定义模板页面留下的评论
<img width="471" alt="image_93" src="https://github.com/liuzhihang/halo-theme-hao/assets/38914772/e1180faf-ebc9-42dd-8dc0-98a3255519db">

2.管理员账户在自定义模板页面以及文章页面留下评论，邮件提醒未收到；评论均会显示在管理后台中

3.额外补充：自定义模板页面留下评论【访客、注册账号、管理员账号】均会在halo日志输出中看到错误日志；管理员账号在文章中留下评论，尽管邮件提醒无法收到，但不会报告错误日志

### 相关日志输出

```shell
2024-03-06T16:01:26.420+08:00 ERROR 7 --- [        task-37] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void run.halo.app.content.comment.CommentNotificationReasonPublisher.onNewComment(run.halo.app.event.post.CommentCreatedEvent)

java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Unknown Source) ~[na:na]
	at run.halo.app.content.comment.CommentNotificationReasonPublisher$NewCommentOnPageReasonPublisher.publishReasonBy(CommentNotificationReasonPublisher.java:161) ~[classes/:2.13.0]
	at run.halo.app.content.comment.CommentNotificationReasonPublisher.onNewComment(CommentNotificationReasonPublisher.java:64) ~[classes/:2.13.0]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351) ~[spring-aop-6.1.4.jar:6.1.4]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.1.4.jar:6.1.4]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.1.4.jar:6.1.4]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.4.jar:6.1.4]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:113) ~[spring-aop-6.1.4.jar:6.1.4]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Comment by Orange-AFK** [comment]
可以确定是主题引起的bug，详情请看：https://github.com/halo-dev/halo/issues/5454

**Comment by Orange-AFK** [comment]
问题解决，弃用halo插件商店的评论模块，自部署artalk评论系统接入主题完美运行；
后来测试了很多个三方主题，前端看独立页面评论都正常，但都是邮件提醒功能抛出错误

**Comment by Orange-AFK** [comment]
close
